name: CI
on: 
  workflow_dispatch:
  push:
jobs:
  build:
    strategy:
      matrix:
        go-version: [latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # - name: Show ENVs before
      #   run: set
      - run: echo "$env:PATH"
      - name: Go version before
        run: go version
      - uses: actions/checkout@v4
      - uses: kevincobain2000/action-gobrew@v2
        with:
          version: ${{ matrix.go-version }}
      - name: Go version after
        run: go version
      - run: echo "$env:PATH"
        shell: bash
      # - name: Show ENVs after
      #   run: set
      #####
      - name: gobrew setup
        run: |
          echo "$HOME\.gobrew\current\bin" >> $env:GITHUB_PATH
          echo "$HOME\.gobrew\bin"  >> $env:GITHUB_PATH
          echo "$HOME\go\bin"  >> $env:GITHUB_PATH
          curl -sLk https://raw.githubusercontent.com/kevincobain2000/gobrew/master/git.io.sh | sh
      - name: gobrew use
        run: gobrew use latest
      # 
      - name: Go version after
        run: go version
        shell: bash
      - run: echo "$env:PATH"
